### ISSUE TITLE
Question: Holodex is the new Craftodex?

### ISSUE THREAD

**Issue by fosterlynn** [open-app/holodex#4]
Hi Simon and Mikey,  we noticed that Craftodex and Directory UI were deprecated in favor of Holodex.  Just curious as to where you guys are going with all of this now, and if you are still using the open vocab for person and organization underneath?

Another thought: Elf and I are going to start in again on the open vocab side, so if you run into anything you want incorporated or don't want incorporated, let us know.

**Comment by ahdinosaur** [comment]
hey @fosterlynn :smiley_cat: 

the "deprecated" status is mostly about old code, although we have gotten more clarity about what we're doing, namely to focus on an app for how we relate to people and groups within a network (before we got lost in the rabbit hole of generic linked data browsing). our goal is to pilot it within [Enspiral](http://enspiral.com) to provide a path for development and see where that takes us. we hope to be the single source of truth for people and group data between [Cobudget](http://cobudget.co) and [Loomio](http://loomio.org), possibly also by providing a single sign-on authentication system. i'm aware at the moment it's not as de-coupled and distributed as say [portable linked profiles](https://github.com/hackers4peace/plp-docs), but our intent is to focus on user value first through minimum viable systems that are used by real networks, then once we have something working we can iterate towards better architectures.

yes, we're still using the [open vocab for people, groups, and relationships](https://github.com/openvocab/holodex) as i hacked with y'all on. while we aren't using my vocab schema system yet, you can see our data [here](https://github.com/holodex/app/tree/master/data) which follows the format.

sweet, if y'all have any major changes to the vocab i'd be keen to hear them, my plan is to continue using the rough structure of [the vocab we worked on](https://github.com/openvocab/holodex), updating for minor changes as necessary. it may also be good to check in every so often, as using the app is informing what the vocab needs to include (such as a `context` property for `Relationship`s, as our stewardships in Enspiral are between two people but under the context of a group).

hope this helps. :sunflower:

**Comment by fosterlynn** [comment]
hey @ahdinosaur (the human one) - thanks much for the reply, I totally get using it in real networks first in more limited form.

You said:  it may also be good to check in every so often, as using the app is informing what the vocab needs to include (such as a context property for Relationships, as our stewardships in Enspiral are between two people but under the context of a group).

Yes, exactly, we need to keep in touch on this!  I'm interested in the requirement for relationships in context of a group.  Let us know how you model/implement that.  I can see we could have some requirement for that, but it has sort of worked because the context is assumed.  Like our herbal network has certain people with responsibility for certain farms, within an assumed context that would actually be better called out.  We have a reference to an agent that we call Context Agent in a lot of other things (processes, events, etc.).  Maybe that is one way to implement on the relationship?  We also know which agents are Context Agents within an installation of NRP, which I think is not part of the vocab we did together because it seemed like a local definition.  But hmmm.

**Comment by bhaugen** [comment]
Watching. And also interested in what you-all do with Skills and Assets (and what they mean).

Lynn had a good explanation of context agents in a recent conversation that I will try to repeat here as best I remember: we don't have an Enterprise or single company that everything is part of, like an ERP system. We don't want to require any particular kind of organizations at all. So context agent takes the place of "the company" or "the department" or whatever is the organization form that people do work in, and that defines a value equation for distributing income.

Lynn, close enough?

**Comment by fosterlynn** [comment]
@bhaugen  Yup close enough.  Maybe worth adding that you can have as many context agents as you want in an installation.  So supporting network of networks and multi-party accounting.

**Comment by ahdinosaur** [comment]
awesome. i'm going to make some issues in [openvocab/holodex](https://github.com/openvocab/holodex) as questions of vocab arise, also we have a scheduled check-in on Wed, March 11, 1pm – 2pm (if anyone reading this wants to join, that's great -> contact me).

>  And also interested in what you-all do with Skills and Assets (and what they mean).

the current plan is to keep our scope focused particularly on relationships (roles), so Skills and Assets are out of scope for now. we'll try to include tags within profiles as a generic interim solution, then as we go we'll include more specific information in profiles.

**Comment by bhaugen** [comment]
" Skills and Assets are out of scope for now" ... good choice...
