### ISSUE TITLE
Holodex user docs

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#47]
we aren't going to be accessible enough for the general public to use yet, but at least we can be somewhat usable for motivated friendly groups to use.
- [ ] write up new user guide
- [ ] write up new group admin guide
- [ ] write up new host admin guide

related to https://github.com/holodex/app/pull/57#issuecomment-93865047.

**Comment by ahdinosaur** [comment]
> Genevieve: Hey holodexers! checkout Tina’s comment in the measuring engagement in Enspiral loomio https://www.loomio.org/d/rP0jVaDA/active-engagement-in-enspiral-how-do-we-measure-it#comment-649472
> > Tina: One of the ways you can measure is by mapping strong/weak relationship links/interactions/connections between people. Is this something Loomio data could do (ideal output is a visual form)?

**Comment by ahdinosaur** [comment]
started a guide for group admins who want to maintain their group's data: https://github.com/open-app/holodex/wiki/Group-admin-guide.

/cc @bhaugen, keen to get feedback from you on what is unclear and confusing, so i know what i should be focusing on.

**Comment by bhaugen** [comment]
@ahdinosaur - thanks for the guide. I'll start trying to use it mid-week, and send feedback.
