### ISSUE TITLE
Shareable urls to filtered view state

### ISSUE THREAD

**Issue by simontegg** [open-app/holodex#63]
Value: Users can share a url in a message and return to that state without having to interact with role and link tags.

Time estimate: working on this part-time in the evenings should take 2 weeks (5th July)

Checkin periodicity: I will checkin and update any observers `1/week`
- [x] define query string format
- [ ] migrate filterered app state to routes

**Comment by simontegg** [comment]
Following [qs](/hapijs/qs) standard formatting I'm going to throw around some ideas. The main idea is that a filters are based on a unified query object `q`. There can be multiple queries `q0` `q1` etc. These `q`'s have properties allowing us to represent semantic triples and visualisation states.  

The properties are:

 `tgt`` "target" and`ctx``` "context". When the target or context is missing and a single context agent is present they are presumed to be the contextagent. 

`role` role: `/groups/craftworks?q0[role]=project-lead` -> show agents that perform the perform the role in relation to or in the context of the context agent -> "project leads of Craftworks" 

`halo` halo: boolean `/groups/craftworks?q0[role]=project-lead&q0[halo]=true` "project leads of Craftworks with halos highlighted" 

`link` link: boolean `/groups/craftworks?q0[role]=steward&q0[halo]=true&q0[link]=true`"stewards of craftworks highlighted with halos and with their stewardees and links to their stewardees present.

`/?a[]=an-agent-id&a[]=another-agent-id` for adhoc combinations of agents.

`/?a[]=loomio&a[]=craftworks&q0[role]=member&q0[tgt]=all&q0[link]=true` -> show the members of both loomio and craftworks with the links between members and their groups. 

use `bool`, `;`, `|`  and `!` to combine queries with boolean operators

`/?q0[role]=member&q0[tgt]=loomio&q1[role]=member&q1[tgt]=craftworks&bool=(q0;q1)` -> "people who are members of loomio AND craftworks (exclude the others).

**Comment by simontegg** [comment]
@ahdinosaur might have bee a while ago but you had some suggestion for how we should handle `linkTypes` ? (currently `roleTypeId + '/link'`)

**Comment by simontegg** [comment]
I keep coming round to roles and links as the main units which have `contexts`,  `pairs` `sources` and `targets` rather than `relationships` having 2 `roles`.

**Comment by ahdinosaur** [comment]
@simontegg can you unpack https://github.com/open-app/holodex/issues/63#issuecomment-116526741?

**Comment by simontegg** [comment]
It might be fine but filters are currently something like a role, link, or agentType + a source, target, or context. "stewards [of person]", "followers  [of person]  _(ie role + target)" "stewards in [context]"  people (related to) [target]" etc. These are the agents on the other side of the relationship.

I would like the data model to have an easy way to get this information. Currently I have to go to the relationship, check the roles, find the the role that doesn't have the source/target/context as its agent.

I tried to make it easier with `pair` on the role but there might be a better way.

**Comment by simontegg** [comment]
I'm going to put a `pairs` derived property on the `agent` -> all the roles with which the agent is in a relationship

**Comment by ahdinosaur** [comment]
:+1:

**Comment by fosterlynn** [comment]
Two cents from the outside: @simontegg I agree that separating out the
roles is probably too high a degree of normalization.  I don't think this
model supports more than two roles on a relationship, and even for a
one-sided relationship like "follow", there is an implicit return
direction, and we can use another method to make clear it is only agreed to
by one party.  I personally would put it all back together.

**Comment by ahdinosaur** [comment]
@fosterlynn are you saying we should re-model [our current `Role` and `Relationship` models](https://github.com/openvocab/holodex/issues/1#issuecomment-81310624)?

if we want to do this, i'm interested in trying out an approach based explicitly on graph nodes and edges. this would be an extensive change, but worth perusing if we feel the current model isn't working. keen to hear more of people's thoughts on this.

**Comment by simontegg** [comment]
Thanks @fosterlynn. 
@ahdinosaur  We've talked about shifting to graph database to assist [the discovery and search value proposition](https://github.com/open-app/holodex/blob/master/comms/value-propositions.md#discovery-and-search) so it makes sense

I'm interested in GraphQL's approach to this
http://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html

https://twitter.com/swannodette/status/563453640330203136
http://hueypetersen.com/posts/2015/02/02/first-thoughts-on-graph-ql/
http://hueypetersen.com/posts/2015/02/08/modeling-queries-graph-ql-like/

**Comment by ahdinosaur** [comment]
the current model _can_ be done in a graph database, it's just maybe not ideal for doing queries, so perhaps our approach for this should be to focus on what our ideal query format is (what this issue is somewhat about) and then see if it's possible to restructure the model to be better suited for those queries using a typical graph database. i'm not sure what model would be better though, our previous approach of directional relationships was very 'graph-y', but then that had problems that lead into our current approach of role-based relationships. i'll need to put this on my back brain for a bit, to see if we can unite the two approaches, maybe roles are agent-like nodes that can be a part of a relationship edge, asdf...

**Comment by simontegg** [comment]
> then see if it's possible to restructure the model to be better suited for those queries using a typical graph database.

+1

> but then that had problems that lead into our current approach 

What were those problems?

**Comment by bhaugen** [comment]
I've done resource flows in graph as well as relational dbs. Ended up going back to relational.

Trade-offs include:
- When I use a relational db, I need to construct directed graphs. The algorithms to do so are well-known. The construction can be slow. For some uses, it would be better to have the whole or at least large parts of the graph be memory-resident (which I've done before, but have not yet done for NRP). Retrieving it from a graph db would be faster than constructing it from a relational db, but not fast enough for many situations, so my pref would be a live memory-resident object graph.
- When I used a graph db, I needed to construct relations (for example, all or selected instances of a type, e.g. Economic Resource, Economic Agent, Economic Event, etc.) Not sure this is true of all graph dbs.
- Relational dbs are a lot more mature and stable than graph dbs. The particular graph db that I used in about 1995, called Tensegrity, is now dead.
- Writes to the graph db were a lot lot lot slower than relational. Managing "dirty" objects in a several thousand node graph db with many changes slowed down everything. That also might be better in more recent graph dbs, but it's something I would test.

P.S. an organization graph is not likely to get as big as a resource flow graph.

**Comment by fosterlynn** [comment]
@simontegg @ahdinosaur I will need to spend a bit more time than I have this morning to respond, we're traveling.  Will do so tomorrow after getting my head back into it deeply enough. 

But generally, I'm not suggesting any big re-modeling, just tweaking the degree of normalization of the model to help with queries, as learned during your implementation.

Also to note, I don't see a problem with specific implementations being different from the standards agreed to for the api, as long as they are compatible and translatable, and done consciously for implementation reasons.  And this thought doesn't diminish the great value of you guys working with the model as people continue to discuss the standard, I'm really really happy you are doing that. :)

But more later....

**Comment by ahdinosaur** [comment]
another point worth mentioning is once we have a proper API i plan to setup our database(s) in a ["kappa architecture"](https://gist.github.com/ahdinosaur/bd1a0005154656217aae). this means all writes are done by adding a transaction to an append-only log, then various "materialized views" listen to these writes and each rebuild respective database indexes for read queries. these "query views" could have entirely different data formats based specifically on the type of query, e.g. relational db, graph db, linked data triple store, etc.

all this being said, my tangent about re-jigging the data model is unrelated to this issue, which can still continue on given our current model. keen to continue the more broader and long-term discussion though. :smile:

**Comment by fosterlynn** [comment]
@simontegg @ahdinosaur  So what I meant was just pulling the Role back into the Relationship, and the same in the type objects.  So every RelationshipType would define the 2 roles (directions) as in earlier models.  Every Relationship would refer to the 2 agents who are related (plus maybe the context agent) - the old "has" and "is".  

I think this would help with querying, but I'm not sure.  I'm a bit lost in the various data persistence implementations talked about in this issue, you guys are not in relational anyway, and I have no experience with graph databases.  And if you are going to generate indexed materialized views of various sorts, maybe it is moot, I don't know.

Hope this helps, and if not, please feel free to ignore! :)

**Comment by simontegg** [comment]
Behold! [Integrated data-model, url querystring and UI design!](https://docs.google.com/drawings/d/1tSWUC4TBXktMbjUcNFX8fDUH_4VdGzLe3Ht0u5K5x-E/edit)

From our catch-up yesterday I think you're right @ahdinosaur that labels like "People who steward {target}" are fundamentally more `link-y` than `role-y`. My confusion was based on these labels not describing the `link` as such. But these labels do describe the `query`. 

In the latest iteration linkTypes (and roleTypes) can have multiple `queryLabels`. Queries are a `linkType` + a `source` || `target` || `context`, or a `roleType` + a `context`. The query pulls out the appropriate label from its [roleType || linkType] depending on how the query is constructed.

**Comment by ahdinosaur** [comment]
@simontegg this is really great, so keen on this direction. :smile:
