### ISSUE TITLE
spreadsheet integration

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#69]
we mentioned in [our last update](https://github.com/open-app/holodex/blob/master/comms/enspiral-services-june-update.md) the possibility of spreadsheet integration as a way to input a group's data into Holodex. a few [potential users have expressed interest](https://github.com/open-app/holodex/issues/56) in such an idea, and i'll admit it's been growing on me. this issue is to track this potential feature, it's not confirmed that we'll pursue it in full but i'm keen to explore the initial design stages.

for this to work, we need a simple format for the data that's accessible to your average spreadsheeteer. as a first pass, i propose the following 3 sheet approach:

1 - group sheet:

| id | holodexToken | name | any | other | profile | properties |
| --- | --- | --- | --- | --- | --- | --- |
| holodex | asdfghjkl | Team Holodex |  |  |  |  |

2 - members sheet:

| id | name | email | roles | any | other | profile | properties |
| --- | --- | --- | --- | --- | --- | --- | --- |
| mikey | Mikey Williams | mikey@example.com | admin |  |  |  |  |
| simon | Simon Tegg | simon@example.com |  |  |  |  |  |

3 - relationships sheet:

| source | link | target |
| --- | --- | --- |
| mikey | stewards | simon |

the problems are that this only works for a single group level, so it wouldn't work for all of Enspiral, just for example Loomio.

:tada:

**Comment by ahdinosaur** [comment]
second pass:

1 - host sheet:

| id | holodexKey |
| --- | --- |
| enspiral | asdfghjkl |

2 - groups sheet:

| id | name | any | other | profile | properties |
| --- | --- | --- | --- | --- | --- |
| foundation | Enspiral Foundation |  |  |  |  |
| services | Enspiral Services |  |  |  |  |
| craftworks | Enspiral Craftworks |  |  |  |  |

3 - people sheet:

| id | name | any | other | profile | properties |
| --- | --- | --- | --- | --- | --- |
| mikey | Mikey Williams |  |  |  |  |
| simon | Enspiral Services |  |  |  |  |

4 - roles sheet:

| context | role | agents |
| --- | --- | --- |
| enspiral | admin | mikey |
| craftworks | treasurer | mikey,simon |

5 - relationships sheet:

| context | source | link | targets |
| --- | --- | --- | --- |
|  | foundation | parent | services |
|  | services | parent | craftworks |
|  | craftworks | group | mikey,simon |
| craftworks | mikey | steward | simon |

hmm...

**Comment by simontegg** [comment]
| role | agent | target | context |
| --- | --- | --- | --- |
| admin | mikey |  | craftworks |
| member | mikey | craftworks |  |
| member | simon | craftworks |  |
| steward | hannah | malcolm | loomio |

The distinction between target and context for a member will be lost on most people

Relationships [see here](/holodex/enspiral-data/pull/16)

| relationship | role | role-label | link-label |
| --- | --- | --- | --- |
| membership | member | People in {target} | belong to {target} |
| membership | group | Groups that include {target} | include {target} |
| stewardship | steward | People that steward {target} | stewards {target} |
| stewardship | stewardee | People that {source} steward | null |

**Comment by ahdinosaur** [comment]
i really like [the direction we're heading of defining links within relationship types](https://github.com/holodex/enspiral-data/pull/16/files) and using them to intuitively define relationships. that's what i meant in my example, sorry for not being more descriptive.

**Comment by ahdinosaur** [comment]
updated to match https://github.com/holodex/enspiral-data/pull/19

5 - relationships sheet:

| context | source | link | targets |
| --- | --- | --- | --- |
|  | services | is-part-of | foundation |
|  | craftworks | is-part-of | services |
|  | craftworks | includes | mikey,simon |
| craftworks | mikey | stewards | simon |

**Comment by simontegg** [comment]
Ilike this arrangement but I prefer to split out each link combination into a separate row:

5 - relationships sheet:

| context | source | link | target |
| --- | --- | --- | --- |
|  | services | is-part-of | foundation |
|  | craftworks | is-part-of | services |
|  | craftworks | includes | mikey |
|  | craftworks | includes | simon |
| craftworks | mikey | stewards | simon |

Conforming to the "long format" structure widely used in tabular data http://www.udel.edu/chs/research/downloads/biostats-guide.pdf

**Comment by simontegg** [comment]
This way the same format works for csv without having to additionally specify a delimiter to use within cells

**Comment by ahdinosaur** [comment]
cool, i'm good with that. :+1: 

i've come to realize spreadsheet integration is probably a better first step towards becoming the canonical source of truth for group data than building an API.

[as mentioned by Rich](https://github.com/open-app/holodex/issues/56#issuecomment-117437113):

> a spreadsheet for all of [my group] would be the best for me, there's something about the spreadsheet that makes me feel safe, it's useful to have a spreadsheet of all the members, it's more scary to put the data into the app as you don't know where it is. anyone knows how to update a spreadsheet, i wouldn't need to on-board anyone.

so i'm considering pausing any work on an API for now and focusing on this.

initial deliverables:
- [x] design tabular data format
- [x] implement polling fetch of data into a normalized format (e.g. with '@type's) ([holodex/app#spreadsheets](https://github.com/holodex/app/tree/spreedsheets))
- [x] implement migration script from yaml to csv ([holodex/app#migrate-yml-to-csv](https://github.com/holodex/app/tree/migrate-yml-to-csv))

**Comment by ahdinosaur** [comment]
naive sheets for types (no nesting):

6 - relationship types sheet

| id | description |
| --- | --- |
| membership | A member may belong to group where the group includes the member. |
| mentorship | A mentor mentors a mentee. |
| stewardship | A steward stewards a stewardee. |
| set | A group may be a parent (superset) or child (subset) of another group. |

7 - role types sheet

| id | label | relationshipType |
| --- | --- | --- |
| member | People in {target} | membership |
| group | Groups that include {target} | membership |
| mentor | People that mentor {target} | mentorship |
| mentee | People that {source} mentors | mentorship |
| steward | People that steward {target} | stewardship |
| stewardee | People that {source} stewards | stewardship |
| parent | Groups that are parents of {target} | set |
| child | Groups that are children of {target} | set |

8 - link types sheet

| id | relationshipType | source | target | label |
| --- | --- | --- | --- | --- |
| belongs-to | membership | member | group | {source} belongs to {target} |
| includes | membership | group | member | {source} includes {target} |
| mentors | mentorship | mentor | mentee | {source} mentors {target} |
| stewards | stewardship | steward | stewardee | {source} stewards {target} |
| is-child-of | membership | child | parent | {source} is child of {target} |
| is-parent-of | membership | parent | child | {source} is parent of {target} |

**Comment by simontegg** [comment]
Can I get an update on this?

**Comment by ahdinosaur** [comment]
haven't made progress since my last checkin.

**deprecated** TODO:
- [ ] get sheet configs working purely through config-able strings / env vars
- [ ] setup deployment sheet
- [ ] migrate yml to sheet
- [ ] test config locally
- [ ] deploy!

**Comment by ahdinosaur** [comment]
[going in a new direction](https://github.com/open-app/holodex/wiki/Group-admin-guide#maintaining-your-group-instance-dream). i'm also dropping support for `.yml` files and instead will focus on sources of tabular data per-type (arrays of objects, e.g. `.csv`, `.ndjson`, `.json`, ...) starting with `.csv`.

TODO (a lot of this is already done, just needs to be cleaned up):
- [x] migrate 'enspiral-data' repo from `.yml` to `.csv`
- [x] create `holodex.enspiral.info` instance repo
- [x] poll data repos for updates
- [x] on update, reset data graph from 'data' dir `.csv` files
- [ ] _bonus_ allow for multiple sources of data
- [x] re-deploy enspiral instance!

**Comment by ahdinosaur** [comment]
done with https://github.com/holodex/app/pull/111
