### ISSUE TITLE
take out the trash

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#72]
it seems we've accumulated a bit of trash in our codebase, such as my terribly hacky `lokijs` + `ampersand-state` model / collection / store system that i threw together after my failed attempt at functional reactive views.

i propose we dedicate a sprint effort into cleaning up our codebase, refactoring our model / collection / store code into beautiful functional reactive immutable views using [nuclear-js](https://github.com/optimizely/nuclear-js), solidifying our [domain model descriptions](https://github.com/openvocab/holodex) and actually using them in our code, and in general focusing on building the best possible app starting from our code craftsmanship.

i reckon it's worth it to do this as it'll make future development more productive and our user-facing experience more snappy, thus raising our upper limit on what can deliver.

best to wait until after #69 and #63 though, just raising the issue now.

**Comment by simontegg** [comment]
++

**Comment by simontegg** [comment]
#63 is  done. 
If this is `in progress`  I advise also completing smaller tasks to maintain morale  and create value for stakeholders other than ourselves and potential other developers.
