### ISSUE TITLE
problem: our ui code is not best practice react + flux

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#81]
this is a subset of https://github.com/open-app/holodex/issues/72.

> it seems we've accumulated a bit of trash in our codebase, such as my terribly hacky `lokijs` + `ampersand-state` model / collection / store system that i threw together after my failed attempt at functional reactive views.
> 
> i propose we dedicate a sprint effort into cleaning up our codebase, refactoring our model / collection / store code into beautiful functional reactive immutable views using [nuclear-js](https://github.com/optimizely/nuclear-js), solidifying our [domain model descriptions](https://github.com/openvocab/holodex) and actually using them in our code, and in general focusing on building the best possible app starting from our code craftsmanship.
> 
> i reckon it's worth it to do this as it'll make future development more productive and our user-facing experience more snappy, thus raising our upper limit on what can deliver.

after recommendations from a few people, i've checked out [redux](https://github.com/rackt/redux) and i must admit it's awesome. it removes the cruft i've disliked in many flux implementations and instead uses pure functions, has [great docs](http://rackt.github.io/redux/), is [funded using Patreon](https://www.patreon.com/reactdx?ty=h), and [has an engaging community](https://github.com/xgrommx/awesome-redux). also turns out the key feature i liked in [nuclear-js](https://github.com/optimizely/nuclear-js), namely [getters](https://optimizely.github.io/nuclear-js/docs/04-getters.html), [is supported in redux with `reselect`](https://www.npmjs.com/package/reselect). so while i put in a small bit of work already with NuclearJS, i'm going to recommend we switch now before we start the brunt of the work.

---
## implementation notes:
- question of what is the structure of a domain module (agent, agent-type, relationship, relationship-type)
  - `actions.js` with [redux-actions](https://github.com/acdlite/redux-actions)
  - `action-types.js` with [create-action-types](https://github.com/chentsulin/create-action-types)
  - `getters.js` with [reselect](https://github.com/faassen/reselect)
  - `reducers.js` with [redux immutable](https://github.com/gajus/redux-immutable)
  - `components/` (dumb components)
  - `containers/` (smart components)
  - `routes.js` with [react-router](https://github.com/rackt/react-router) and [redux-react-router](https://github.com/acdlite/redux-react-router)
- do we want to use [RxJS](https://github.com/acdlite/redux-rx)?
- do we want to use [transducers](https://github.com/acdlite/redux-transducers)?

**Comment by simontegg** [comment]
Should we have only one 'smart' component? `app.js``. Or a smart component for each view mode?`graph-view.js```

**Comment by ahdinosaur** [comment]
i'm thinking a smart component for each route.

**Comment by ahdinosaur** [comment]
although i'm not 100% sure what routing system we want, [react-router](http://rackt.github.io/react-router/) works well with redux (from the same people, also improvements incoming with [react-router#modular](https://github.com/rackt/react-router/tree/modular) and [redux-react-router#1](https://github.com/acdlite/redux-react-router/issues/1)), so we could have each domain module export routes that use that module's  "containers" (a term for smart components i've been seeing used in examples) which we can compose together at the top, or something else.

**Comment by bhaugen** [comment]
Once you settle down, and I get time, I'll start to follow your example. Want to work on the visual network explorer to follow the arms and legs of the holodex nodes.

**Comment by ahdinosaur** [comment]
btw, @simontegg https://github.com/gajus/canonical-reducer-composition/issues/4#issuecomment-136539632.

**Comment by bhaugen** [comment]
Please explain wtf is a reducer? I looked around that link and its connections and everything seems to assume that you know what it is. The code examples didn't help me either. I must be getting old and out of touch...

**Comment by simontegg** [comment]
Javascript has an `Array.reduce(reducerCallback)` https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

That's quite quite handy for filtering and mapping data in the same function.

**Comment by bhaugen** [comment]
thx, that helps me continue to dig.

**Comment by simontegg** [comment]
A smart component for each route `/agent/` `/relationship` etc doesn't make sense to me. Isn't the idea these are containers passing props down to dumb components?  What are the child components of an agent component? Graph contains both agents and relationships. So does a list etc . Seems to make more sense.

**Comment by ahdinosaur** [comment]
@simontegg containers are akin to a page, so the child components of a agent container (page) would be agents and relationships, laid out in either a graph or a list or whatever. having containers for the different modes (graph, list, etc) is an interesting idea, i'm not sure how that'd work for domains that don't make sense in either (AgentType, RelationshipType, ...) so it seems intuitively better to compose those components into domain-specific containers, but i have no idea.

**Comment by simontegg** [comment]
I still don't get it. Can you sketch an example component hierarchy?

**Comment by ahdinosaur** [comment]
just spit-balling:

``` yml
AgentContainer:
  Graph:
    Query:
      AgentQuery:
    Nodes:
      Agent:
      Agent:
    Edges:
      Relationship:
    Legend:
      LegendItem:
```

**Comment by ahdinosaur** [comment]
i imagine `AgentContainer` component to be similar to how we did [group/views/page](https://github.com/holodex/app/blob/master/src/node_modules/group/views/page.js) or [person/views/page](https://github.com/holodex/app/blob/master/src/node_modules/person/views/page.js).

**Comment by ahdinosaur** [comment]
for the logs,

i had an in-person convo with @simontegg about as part of this refactor using [anvaka](https://github.com/anvaka)'s [`ngraph` ecosystem](https://github.com/anvaka/ngraph) for layouts and more instead of webcola. then a Slack convo:

> Simon Tegg: @ahdinosaur: can you point me in the direction of anvaka's comments about updating graphs then tweening
> Mikey Williams: uhhh.. what are you hoping to get from it?
> Mikey Williams: https://github.com/gouldingken/pixi-ngraph#smoothing
> Mikey Williams: https://github.com/anvaka/ngraph.asyncforce#usage
> Mikey Williams: @simontegg: does that help? i might have imagined some of it, but i think it'd be pretty straightforward to do X number of layout cycles before the initial render, then do Y layout cycles then tween from initial to new position, then repeat until new positions don't change much. thoughts? (we should ideally move this discussion to a GitHub issue)
> Mikey Williams: also for managing the tween ticks: https://www.npmjs.com/package/tween-ticker
> Simon Tegg: sweet ta
