### ISSUE TITLE
problem: api and ui are coupled

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#83]
we should split `app` into `api` and `ui`.

TODO
- [ ] `api` (service)
- [ ] `ui` (static site)

**Comment by ahdinosaur** [comment]
i think i'm going to punt on this until after we compost `app`.

**Comment by ahdinosaur** [comment]
as a note, one tactic i'm thinking to make this happen would be for the `api` and `ui` to interact over [a common data format](https://github.com/openvocab/agent). this way, we aren't limited to interfacing with only our own `api`, the `ui` could work with any compatible `api`, such as [NRP's shiny new JSON-LD api](https://github.com/openvocab/agent/issues/20). for [incompatible but important data](#76), the [`api` could do some stream magic to transform input into the proper format](https://github.com/openvocab/meta/issues/1).

curious what you think @simontegg, the above approach seems nice in drawing a clear line between back and front ends, not sure if that's good or bad since hopefully we'd share code across the entire stack. 

props to @elf-pavlik for championing this approach in [personal linked profiles](https://github.com/hackers4peace/plp-docs).

**Comment by simontegg** [comment]
Yes I like the split approach for ease of compatibility with other software

**Comment by elf-pavlik** [comment]
I used decoupled apps (GUIs) and deamons (APIs) already in 2nd generation of DSpace(-NG) prototypes https://github.com/dspace-ng

Both apps and and daemons use certain APIs, while apps only **act as client** daemons mostly **act as server** but sometimes **also act as client** (one of the reasons I prefer to use app/deamon terminology and not client/server)
